### ISSUE TITLE
Gulp Vue-strap Laravel

### ISSUE THREAD

**Issue by Vahan94** [yuche/vue-strap#366]
I want to add vue-strap with gulp but get errors

ReferenceError: window is not defined
    at Object.<anonymous> (C:\xampp\htdocs\moondance\node_modules\vue-strap\dist\vue-strap.js:1137:6)
    at __webpack_require__ (C:\xampp\htdocs\moondance\node_modules\vue-strap\dist\vue-strap.js:30:30)
    at Object.defineProperty.value (C:\xampp\htdocs\moondance\node_modules\vue-strap\dist\vue-strap.js:59:18)
    at __webpack_require__ (C:\xampp\htdocs\moondance\node_modules\vue-strap\dist\vue-strap.js:30:30)
    at C:\xampp\htdocs\moondance\node_modules\vue-strap\dist\vue-strap.js:50:18
    at C:\xampp\htdocs\moondance\node_modules\vue-strap\dist\vue-strap.js:53:10
    at webpackUniversalModuleDefinition (C:\xampp\htdocs\moondance\node_modules\vue-strap\dist\vue-strap.js:3:20)
    at Object.<anonymous> (C:\xampp\htdocs\moondance\node_modules\vue-strap\dist\vue-strap.js:10:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by wffranco** [comment]
I always get error in npm when I include it, but in the end always is added, so I don't know the reason but if work I don't care so much about it :laughing:
