### ISSUE TITLE
fail to rebuild vue-strap

### ISSUE THREAD

**Issue by rabe69** [yuche/vue-strap#405]
After installing current V2 Branch and `npm install && npm run build` I get this error:
```
module.js:442
    throw err;
    ^

Error: Cannot find module '/Users/alex/Projects/vuestrap-test/node_modules/vue-strap/webpack.build.min.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/alex/Projects/vuestrap-test/node_modules/vue-strap/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/Users/alex/Projects/vuestrap-test/node_modules/vue-strap/node_modules/webpack/bin/webpack.js:39:40)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

**Comment by rabe69** [comment]
My fault. I used npm version, which does not include all files.
