### ISSUE TITLE
failed to use "npm run docs"

### ISSUE THREAD

**Issue by rabe69** [yuche/vue-strap#406]
After installing current V2 branch and enter `npm run docs` on my console I get this error:
```
/Users/alex/Projects/vuestrap-test/node_modules/vue-strap/node_modules/webpack/lib/NormalModuleFactory.js:72
			var elements = request.replace(/^-?!+/, "").replace(/!!+/g, "!").split("!");
			                      ^

TypeError: Cannot read property 'replace' of undefined
    at /Users/alex/Projects/vuestrap-test/node_modules/vue-strap/node_modules/webpack/lib/NormalModuleFactory.js:72:26
    at /Users/alex/Projects/vuestrap-test/node_modules/vue-strap/node_modules/webpack/lib/NormalModuleFactory.js:28:4
    at /Users/alex/Projects/vuestrap-test/node_modules/vue-strap/node_modules/webpack/lib/NormalModuleFactory.js:159:3
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/alex/Projects/vuestrap-test/node_modules/vue-strap/node_modules/tapable/lib/Tapable.js:75:69)
    at NormalModuleFactory.create (/Users/alex/Projects/vuestrap-test/node_modules/vue-strap/node_modules/webpack/lib/NormalModuleFactory.js:144:8)
    at /Users/alex/Projects/vuestrap-test/node_modules/vue-strap/node_modules/webpack/lib/Compilation.js:214:11
    at /Users/alex/Projects/vuestrap-test/node_modules/vue-strap/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/Users/alex/Projects/vuestrap-test/node_modules/vue-strap/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/Users/alex/Projects/vuestrap-test/node_modules/vue-strap/node_modules/async/lib/async.js:209:22)
    at Compilation.addModuleDependencies (/Users/alex/Projects/vuestrap-test/node_modules/vue-strap/node_modules/webpack/lib/Compilation.js:185:8)
```

**Comment by rabe69** [comment]
My fault. I used npm version, which does not include all files.
