### ISSUE TITLE
Uncaught TypeError: (0 , _NodeList2.default) is not a function

### ISSUE THREAD

**Issue by gholol** [yuche/vue-strap#434]
I get error each time I try to use bs-input component inside modal. Modal itself works fine.

I'm using Vue 1 + chome 55

Uncaught TypeError: (0 , _NodeList2.default) is not a function
    at VueComponent.ready (eval at <anonymous> (http://localhost/build/assets/js/app-1782b5ab2d.js:447:1), <anonymous>:363:28)
    at VueComponent.Vue._callHook (eval at <anonymous> (http://localhost/build/assets/js/app-1782b5ab2d.js:1171:1), <anonymous>:8399:21)
    at VueComponent.ready (eval at <anonymous> (http://localhost/build/assets/js/app-1782b5ab2d.js:1171:1), <anonymous>:9628:10)
    at VueComponent.on (eval at <anonymous> (http://localhost/build/assets/js/app-1782b5ab2d.js:1171:1), <anonymous>:9425:10)
    at VueComponent.Vue.$emit (eval at <anonymous> (http://localhost/build/assets/js/app-1782b5ab2d.js:1171:1), <anonymous>:9506:22)
    at VueComponent.Vue._callHook (eval at <anonymous> (http://localhost/build/assets/js/app-1782b5ab2d.js:1171:1), <anonymous>:8402:10)
    at callAttach (eval at <anonymous> (http://localhost/build/assets/js/app-1782b5ab2d.js:1171:1), <anonymous>:8361:13)
    at Array.forEach (native)
    at VueComponent.onAttached (eval at <anonymous> (http://localhost/build/assets/js/app-1782b5ab2d.js:1171:1), <anonymous>:8349:22)
    at VueComponent.Vue.$emit (eval at <anonymous> (http://localhost/build/assets/js/app-1782b5ab2d.js:1171:1), <anonymous>:9506:22)

**Comment by ADRDev** [comment]
Did you ever resolve this? I'm facing a similar issue.
