### ISSUE TITLE
SSR (Server Side Rendering)

### ISSUE THREAD

**Issue by wormen** [yuche/vue-strap#456]
how to use your plugin with SSR?
at the moment this is not possible, because I get the error
```
ReferenceError: window is not defined
```

**Comment by wffranco** [comment]
Your information is not enough to know what are you doing.

**Comment by wormen** [comment]
@wffranco to get this error, connect the component enough

**Comment by cawa-93** [comment]
The same problem. I use nuxt with CoreUI theme. 
When I try import 
```javascript
import navbar from './Navbar'
import { dropdown } from 'vue-strap'

export default {
  name: 'header',
  components: {
    navbar,
    dropdown
  },
  methods: {
    click () {
      // do nothing
    },
    sidebarToggle (e) {
      e.preventDefault()
      document.body.classList.toggle('sidebar-hidden')
    },
    mobileSidebarToggle (e) {
      e.preventDefault()
      document.body.classList.toggle('sidebar-mobile-show')
    },
    asideToggle (e) {
      e.preventDefault()
      document.body.classList.toggle('aside-menu-hidden')
    }
  }
}
```
I get error
```javascript
ReferenceError: self is not defined
    at Object.defineProperty.value (/home/alex/LinWin/Develop/fb-scaner/node_modules/vue-strap/dist/vue-strap.js:1773:20)
    at __webpack_require__ (/home/alex/LinWin/Develop/fb-scaner/node_modules/vue-strap/dist/vue-strap.js:30:30)
    at Object.&lt;anonymous&gt; (/home/alex/LinWin/Develop/fb-scaner/node_modules/vue-strap/dist/vue-strap.js:265:2)
    at __webpack_require__ (/home/alex/LinWin/Develop/fb-scaner/node_modules/vue-strap/dist/vue-strap.js:30:30)
    at Object.defineProperty.value (/home/alex/LinWin/Develop/fb-scaner/node_modules/vue-strap/dist/vue-strap.js:59:18)
    at __webpack_require__ (/home/alex/LinWin/Develop/fb-scaner/node_modules/vue-strap/dist/vue-strap.js:30:30)
    at /home/alex/LinWin/Develop/fb-scaner/node_modules/vue-strap/dist/vue-strap.js:50:18
    at /home/alex/LinWin/Develop/fb-scaner/node_modules/vue-strap/dist/vue-strap.js:53:10
    at webpackUniversalModuleDefinition (/home/alex/LinWin/Develop/fb-scaner/node_modules/vue-strap/dist/vue-strap.js:3:20)
    at Object.&lt;anonymous&gt; (/home/alex/LinWin/Develop/fb-scaner/node_modules/vue-strap/dist/vue-strap.js:10:3)
```

**Comment by PierreRambaud** [comment]
:+1:  Same problem here, some components can't be rendered with SSR

**Comment by canhongpoxiao** [comment]
@PierreRambaud Hi friend, I get the same problem, but I don't know how to solve it, can you said some details. Thanks

**Comment by ShmidtAlex** [comment]
Vote up for issue. It is still here.

**Comment by n-sikka** [comment]
Getting the exact same error as the `dropdown` one above. Is there any update on this issue? 
Any plans for SSR support?

**Comment by mymtw** [comment]
Not working ssr
```
error during render : /
ReferenceError: window is not defined
```
